apiVersion: webapp.hfgary.io/v1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-sample
spec:
  # TODO(user): Add fields here
  size: 3
  configMapName: guestbook-config
  type: example

